export default {
	background_images: [
		'src/img/bg/bg-1.jpg',
		'src/img/bg/bg-2.jpg',
		'src/img/bg/bg-3.jpg',
		'src/img/bg/bg-4.jpg',
		'src/img/bg/bg-5.jpg',
		'src/img/bg/bg-6.jpg',
		'src/img/bg/bg-7.jpg',
		'src/img/bg/bg-8.jpg',
		'src/img/bg/bg-9.jpg',
		'src/img/bg/bg-10.jpg',
		'src/img/bg/bg-11.jpg',
		'src/img/bg/bg-12.jpg',
		'src/img/bg/bg-13.jpg',
		'src/img/bg/bg-14.jpg',
		'src/img/bg/bg-15.jpg',
		'src/img/bg/bg-16.jpg',
		'src/img/bg/bg-17.jpg',
		'src/img/bg/bg-18.jpg',
		'src/img/bg/bg-19.jpg',
		'src/img/bg/bg-20.jpg',
		'src/img/bg/bg-21.jpg',
		'src/img/bg/bg-22.jpg',
		'src/img/bg/bg-23.jpg',
		'src/img/bg/bg-24.jpg',
		'src/img/bg/bg-25.jpg',
		'src/img/bg/bg-26.jpg',
		'src/img/bg/bg-27.jpg',
		'src/img/bg/bg-28.jpg',
	],
	attacker: [{ x: 214, y: 425 }, { x: 384, y: 115 }, { x: 584, y: 425 }],
	defender: [{ x: 900, y: 425 }, { x: 1088, y: 115 }, { x: 1264, y: 425 }],
	canvas: document.getElementById('canvas'),
	delayAfterEndFight: 3000,

};
